### PR TITLE
Moved moderated channels list to env

### PR DESCRIPTION
**Pull request by justetz**
Moved the definition of the moderated channels (previously hard-coded in a switch statement) to a new environment variable, `MODERATED_CHANNELS`. This eliminates the need for code changes if/when the list of moderated channels changes.

## Spec for the new environment variable: `MODERATED_CHANNELS`

Channel names should match what they appear as in Slack and should be comma separated with no whitespace. For example, if `#general`, `#alerts`, `#random`, and `#scheduling` are moderated, then the env definition should be:

```
MODERATED_CHANNELS=general,alerts,random,scheduling
```

Or in any order desired.

### CODE REVIEW

**Comment by ddbruce** [comment]
This looks ok, but env vars have to be set in our deployment(s), of course. Wait to merge until that's done.

**Comment by lramos15** [comment]
I still believe at some point we need to move to channel IDs instead of names in the rare event of channel renaming, but that's a separate PR. This LGTM

**Comment by ddbruce** [comment]
It would be cool to add a command to add or remove moderation. It'd be less for our use and more for if someone forked it. I think that feature would pretty much _never_ be used in our case.

I added this var to the Docker config for the dev deployment with the channels @justetz listed above. I'll merge this so we can test that it works.

**Comment by justetz** [comment]
I agree that the command for adding moderated channels would be a great addition. However, there would need to be some kind of DB or means of ensuring that the new entries persist between container restarts.

**Pull request merged**
